version: "2.3"
services:
  app:
    image: openpose-python:latest
    build: .
    runtime: nvidia
    volumes:
      - /etc/localtime:/etc/localtime
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app

    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    stdin_open: true
    tty: true

